### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by nctlcnt** [nctlcnt/player#2]
- [ ] PC端布局
- [x] 移动端布局调整
- [ ] 加载时显示loading
- [ ] 加载后显示缓冲条

**Comment by ruoooo** [comment]
- [ ] cover模糊后错位

**Comment by nctlcnt** [comment]
- [ ] 接入网易云api

**Comment by nctlcnt** [comment]
- [ ] ！云服务器文件更新
- [ ] nginx做分移动端和pc端适配
